# Generated by Django 6.0 on 2026-01-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name_plural': 'Товары в заказах'},
        ),
    ]
