# Generated by Django 6.0 on 2026-01-01 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=120)),
                ('product_name', models.CharField(choices=[('Ботинки', 'Ботинки'), ('Кеды', 'Кеды'), ('Кроссовки', 'Кроссовки'), ('Полуботинки', 'Полуботинки'), ('Сапоги', 'Сапоги'), ('Тапочки', 'Тапочки'), ('Туфли', 'Туфли')], max_length=120)),
                ('unit_of_measurement', models.CharField(choices=[('шт.', 'шт.')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(choices=[('Женская обувь', 'Женская обувь'), ('Мужская обувь', 'Мужская обувь')], max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=400)),
                ('photo', models.ImageField(upload_to='')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', related_query_name='manufacturer', to='company.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', related_query_name='supplier', to='company.company')),
            ],
        ),
    ]
