# Generated by Django 6.0 on 2026-01-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='picture.png', null=True, upload_to=''),
        ),
    ]
