# Generated by Django 6.0 on 2026-01-03 10:08

import django.core.validators
import django_resized.forms
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='picture.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 200], upload_to=''),
        ),
    ]
