# Generated by Django 6.0 on 2026-01-15 17:48

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_alter_company_name'),
        ('product', '0006_alter_product_discount_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', related_query_name='manufacturer', to='company.company', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, default='picture.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 200], upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Женская обувь', 'Женская обувь'), ('Мужская обувь', 'Мужская обувь')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('Ботинки', 'Ботинки'), ('Кеды', 'Кеды'), ('Кроссовки', 'Кроссовки'), ('Полуботинки', 'Полуботинки'), ('Сапоги', 'Сапоги'), ('Тапочки', 'Тапочки'), ('Туфли', 'Туфли')], max_length=120, verbose_name='Наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=120, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', related_query_name='supplier', to='company.company', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(choices=[('шт.', 'шт.')], max_length=20, verbose_name='Единица измерения'),
        ),
    ]
