# Generated by Django 6.0 on 2026-01-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name_plural': 'Пункты выдачи заказов'},
        ),
    ]
